from pydantic import BaseModel, Field
from typing import Dict

class GridSettings(BaseModel):
    total_capacity_kwh: float = Field(default=1000.0, description="Total available power capacity in kWh per hour")
    normal_price_per_kwh: float = Field(default=0.15, description="Price per kWh during normal hours in USD")
    peak_price_per_kwh: float = Field(default=0.30, description="Price per kWh during peak hours in USD")
    co2_kg_per_kwh: float = Field(default=0.5, description="CO2 emissions in kg per kWh consumed")
    green_energy_fraction: float = Field(default=0.3, description="Fraction of energy generated by campus solar/wind")

class AgentWeights(BaseModel):
    satisfaction: float = Field(default=0.5, description="Weight w1 for agent demand satisfaction")
    sustainability: float = Field(default=0.3, description="Weight w2 for energy saving/sustainability")
    cost: float = Field(default=0.2, description="Weight w3 for carbon/electricity cost savings")

class ClassroomAgentSettings(BaseModel):
    base_occupancy: int = Field(default=300, description="Average classroom occupancy")
    base_power_per_person_kw: float = Field(default=0.15, description="Base power draw in kW per person (lights, AC)")
    hvac_power_kw: float = Field(default=50.0, description="HVAC baseline power draw in kW")

class LaboratoryAgentSettings(BaseModel):
    machine_count: int = Field(default=50, description="Number of heavy research machines/servers")
    avg_power_per_machine_kw: float = Field(default=1.2, description="Average power draw per active machine in kW")
    baseload_kw: float = Field(default=30.0, description="Baseload of laboratories (servers, ventilation)")

class HostelAgentSettings(BaseModel):
    resident_count: int = Field(default=1200, description="Number of hostel residents")
    base_power_per_resident_kw: float = Field(default=0.2, description="Base energy request in kW per resident")
    appliance_power_kw: float = Field(default=80.0, description="Power draw from shared hostel appliances")

class RLSettings(BaseModel):
    learning_rate: float = Field(default=0.1, description="Learning rate alpha")
    discount_factor: float = Field(default=0.9, description="Discount factor gamma")
    epsilon: float = Field(default=0.1, description="Exploration rate for epsilon-greedy action selection")
    epsilon_decay: float = Field(default=0.995, description="Decay rate for epsilon")
    epsilon_min: float = Field(default=0.01, description="Minimum exploration rate")

class SimulationSettings(BaseModel):
    duration_days: int = Field(default=30, description="Duration of simulation in days (30, 100, 365)")
    seed: int = Field(default=42, description="Random seed for reproducibility")

class AppConfig(BaseModel):
    grid: GridSettings = Field(default_factory=GridSettings)
    weights: AgentWeights = Field(default_factory=AgentWeights)
    classroom: ClassroomAgentSettings = Field(default_factory=ClassroomAgentSettings)
    laboratory: LaboratoryAgentSettings = Field(default_factory=LaboratoryAgentSettings)
    hostel: HostelAgentSettings = Field(default_factory=HostelAgentSettings)
    rl: RLSettings = Field(default_factory=RLSettings)
    simulation: SimulationSettings = Field(default_factory=SimulationSettings)

# Global default config instance
default_config = AppConfig()
